import { IBoardPagePageObject, SwimlaneElement } from './BoardPage';

export const BoardPagePageObjectMock: IBoardPagePageObject = {
  selectors: {
    pool: '#ghx-pool',
    issue: '.ghx-issue',
    flagged: '.ghx-flagged',
    grabber: '.ghx-grabber',
    grabberTransparent: '.ghx-grabber-transparent',
    sidebar: '.ghx-sidebar',
    column: '.ghx-column',
    columnHeader: '.ghx-column-header',
    columnTitle: '.ghx-column-title',
    daysInColumn: '.ghx-days',
    swimlaneHeader: '.ghx-swimlane-header',
    swimlaneRow: '.ghx-swimlane',
  },
  classlist: {
    flagged: 'ghx-flagged',
  },
  getColumns: () => ['To Do', 'In Progress', 'Done'],
  listenCards: () => () => {},
  getColumnOfIssue: () => '',
  getDaysInColumn: () => null,
  hideDaysInColumn: () => {},
  getHtml: () => '',
  getSwimlanes: (): SwimlaneElement[] => [],
  getSwimlaneHeader: () => null,
  getIssueCountInSwimlane: () => 0,
  getIssueCountByColumn: () => [],
  getIssueCountForColumns: () => 0,
  insertSwimlaneComponent: () => {},
  removeSwimlaneComponent: () => {},
  highlightSwimlane: () => {},
};
