---
name: "pre-release"

on:
  push:
    branches:
      - "master"
      - "pre-release-beta"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Lint, Test & Build
        run: |
          npm ci
          npm run lint
          npm test
          npm run prod
          mv jira-helper.zip jira-helper-canary.zip
          npm run prod:firefox
          mv jira-helper-firefox.zip jira-helper-firefox-canary.zip
        env:
          CI: true

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "canary"
          prerelease: true
          title: "Development Build"
          files: |
            jira-helper-canary.zip
            jira-helper-firefox-canary.zip
